# Generated by Django 4.0 on 2022-01-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=10000)),
                ('option_a', models.CharField(max_length=1000)),
                ('option_b', models.CharField(max_length=1000)),
                ('option_c', models.CharField(max_length=1000)),
                ('option_d', models.CharField(max_length=1000)),
                ('correct', models.CharField(max_length=1000)),
            ],
        ),
    ]
