# Generated by Django 4.0 on 2022-01-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='q_no',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
