# Generated by Django 4.0 on 2022-01-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_questions_q_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
