# Generated by Django 4.0.1 on 2022-02-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_questions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('1', 'Choice a subject'), ('English', 'English'), ('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer', 'Computer')], default='1', max_length=20),
        ),
    ]
