# Generated by Django 4.0.1 on 2022-02-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_questions_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='q_no',
        ),
    ]
