# Generated by Django 4.0 on 2022-03-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0008_remove_questions_q_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('profession', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('english_no', models.IntegerField(default=0)),
                ('math_no', models.IntegerField(default=0)),
                ('physics_no', models.IntegerField(default=0)),
                ('chemistry_no', models.IntegerField(default=0)),
                ('computer_no', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
