# Generated by Django 4.0 on 2022-03-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_custom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
