# Generated by Django 4.0 on 2022-03-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_custom_user_avg_custom_user_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='avg',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='total',
        ),
    ]
