# Generated by Django 4.0 on 2022-03-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_examinee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
        migrations.RenameField(
            model_name='custom_user',
            old_name='profession',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='chemistry_no',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='computer_no',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='english_no',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='math_no',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='physics_no',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='father',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custom_user',
            name='mobile',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
