# Generated by Django 4.0 on 2022-03-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_contact_delete_subscribe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
